import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import TopTab from "../components/TopTab/TopTab";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Unicial Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TopTab />
    </div>
  );
};

export default Home;
