import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Header from "../../components/Header/Header";
import TopTab from "../../components/TopTab/TopTab";
import Announcements from "../../components/Layout/Announcements";
import NewsLetter from "../../components/NewsLetter/NewsLetter";
import SocialLinkBlock from "../../components/SocialLinkBlock/SocialLinkBlock";
import Footer from "../../components/Footer/Footer";
//
import BlogDetail from "./[slug]";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Unicial Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
          crossOrigin="anonymous"
        />
      </Head>
      <Header />
      <TopTab />
      <Announcements />
      {/* <BlogDetail /> */}
      <NewsLetter />
      <SocialLinkBlock />
      <Footer />
    </div>
  );
};

export default Home;
